### ISSUE TITLE
router: error associating user secret: persistence: error creating user: relational: error creating secret: Error 1406: Data too long for column 'encrypted_secret' at row 1

### ISSUE THREAD

**Issue by mlespiau** [offen/offen#465]
Hi, 

I just setup a fresh installation of offen and set it up to track analytics from one of my sites. Once I copy the tracking code, I see that no data is coming to the site. After some debugging I found that the exchange requests is failing with a 400 HTTP status code and the following error message in the response: 

`router: error associating user secret: persistence: error creating user: relational: error creating secret: Error 1406: Data too long for column 'encrypted_secret' at row 1`

In the request, I can see that secret being sent is 689 characters long and in mysql the encrypted_secret is a 255 var char. 

I updated the varchar limit to 1000 for the encrypted_secret column and the problem seems to be fixed (as for now). 

I'm using official docker image v0.1.4 and mariadb 10.4.13. 

I would like to know what's a good varchar limit for the encrypted_secret column, or, if the value is correct, what's wrong with my site which is generating longer encrypted secrets.

Thanks!

**Comment by m90** [comment]
Thanks for the detailed report. Your observation is pretty much correct. The `encrypted_secret` is expected to be the 689 characters of length you are observing, so there's nothing unexpected happening here.

The fix is probably just a matter of making the field `type:"text"`: 

https://github.com/offen/offen/blob/f5b793ad397b06fba044901305c894b72a0d0969/server/persistence/relational/models.go#L75-L78

and adding a migration for the table. I'll include this in the `v0.1.5` release which we'll probably do later this week.

---

The part that I don't get yet is that I've already installed (older versions of) Offen against MariaDB which worked fine and we also run integration tests against MySQL so finding out how this regression got introduced will be interesting.

**Comment by m90** [comment]
I was able to reproduce this issue using the following setup

```yml
version: '3'

services:
  offen:
    image: offen/offen:v0.1.4
    ports:
      - 8888:80
    environment:
      OFFEN_DATABASE_DIALECT: mysql
      OFFEN_DATABASE_CONNECTIONSTRING: root:secret@tcp(mysql:3306)/offen?parseTime=true
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.4.13
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: offen
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mariadb_data:
```

Applying the changes from #466 made it work as expected.
