### ISSUE TITLE
Retry connecting to database before giving up

### ISSUE THREAD

**Issue by m90** [offen/offen#470]
Offen can connect to MySQL/MariaDB or Postgres databases for storing data.

On startup a database connection is established and will be used from thereon. In case this does not work, Offen exits. This will however create problems in docker-compose setups where especially MySQL containers will be `up` before they actually accept connections.

At the moment working around this requires custom scripting, making sure the `offen/offen` container is does not run the `offen` command before MySQL actually accepts the connection.

Instead, we can add a `-retries <num>` flag to the serve command that will make Offen retry establishing the database connection before giving up.

---

This is an example setup for reproducing the behavior:

```yml
version: '3'

services:
  offen:
    image: offen/offen:latest
    ports:
      - 8888:80
    environment:
      OFFEN_DATABASE_DIALECT: mysql
      OFFEN_DATABASE_CONNECTIONSTRING: root:secret@tcp(mysql:3306)/offen?parseTime=true
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.4.13
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: offen
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mariadb_data:
```
