### ISSUE TITLE
The arm64 image is missing in the docker tags

### ISSUE THREAD

**Issue by strootje** [offen/offen#685]
Hi,

I'd like to be able to run this on a rasberrypi. But there is no arm64 build.
It looks like you are using a cross-compiler for go (xgo). it does have options to add arm64 (`--targets=linux/arm64`)

could it be as simple as this?
.circleci/config.yml
```yml
//...
  build:
    executor: python
    working_directory: ~/offen
    environment:
      DOCKER_LOGIN: offen
      DOCKER_BUILDKIT: '1'
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Set revision
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              echo 'export OFFEN_GIT_REVISION=$(git rev-parse --short HEAD)' >> $BASH_ENV
            else
              echo 'export OFFEN_GIT_REVISION=$CIRCLE_TAG' >> $BASH_ENV
            fi
      - run:
          name: Build binaries
          command: |
            if [ -z "$CIRCLE_TAG" ] && [ "${CIRCLE_BRANCH}" != "development" ] && [ "${CIRCLE_BRANCH}" != "master" ]; then
              make build
            else
---           TARGETS=linux/amd64,windows/amd64 make build
+++           TARGETS=linux/amd64,windows/amd64,linux/arm64 make build
              # Darwin builds cannot be statically linked right now
              # so we override the default LDFLAGS value
              TARGETS=darwin/amd64 LDFLAGS='' make build
            fi
      - persist_to_workspace:
          root: ~/offen
          paths:
            - bin/*
//...
```

Would love to hear your thoughts on this
